<?php

	function cashFreePaymentVerification($order_id, $is_test){

        $url = "https://api.cashfree.com/api/v1/order/info/status";
        
        if($is_test){
            $url = "https://test.cashfree.com/api/v1/order/info/status";
        }

        $curl = curl_init();

        $params = "appId=Your Production ID From Cash Free".
            "&secretKey=Your Production Secret From Cash Free".
            "&orderId=".$order_id;

        if($is_test){
            $params = "appId=Your Test ID From Cash Free".
                "&secretKey=Your Test Secret From Cash Free".
                "&orderId=".$order_id;
        }

        curl_setopt_array($curl, array(
          CURLOPT_URL => $url,
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => "",
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 0,
          CURLOPT_FOLLOWLOCATION => true,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => "POST",
          CURLOPT_SSL_VERIFYHOST => 0,
          CURLOPT_SSL_VERIFYPEER => 0,
          CURLOPT_POSTFIELDS => $params,
            CURLOPT_HTTPHEADER => array(
              "Content-Type: application/x-www-form-urlencoded"
            ),
        ));

        $response = curl_exec($curl);

        curl_close($curl);
        
        return trim($response);
    }

    // Order ID to be generated by your server
    echo json_encode(cashFreePaymentVerification($_POST['order_id'], true))

?>