<?php

	function cashFreeOrderTokenGeneration( $order_id, $order_amount, $order_currency, $is_test){

    	$url = "https://api.cashfree.com/api/v2/cftoken/order";
    	if($is_test){
    		$url = "https://test.cashfree.com/api/v2/cftoken/order";
    	}

    	$curl = curl_init();

    	$params = "{\r\n  \"orderId\": \"" .$order_id. "\",\r\n  \"orderAmount\":".$order_amount.",\r\n  \"orderCurrency\":\"".$order_currency."\"\r\n}";

    	$headers = array(
			"x-client-id: Your Production ID From Cash Free",
			"x-client-secret: Your Production Secret From Cash Free",
			"Content-Type: application/json"
		);

		if($is_test){
	    	$headers = array(
				"x-client-id: Your Test ID From Cash Free",
				"x-client-secret: Your Test Secret From Cash Free",
				"Content-Type: application/json"
			);
		}

    	// echo $params;

    	curl_setopt_array($curl, array(
    	  CURLOPT_URL => $url,
    	  CURLOPT_RETURNTRANSFER => true,
    	  CURLOPT_MAXREDIRS => 10,
    	  CURLOPT_TIMEOUT => 0,
    	  CURLOPT_FOLLOWLOCATION => true,
    	  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    	  CURLOPT_SSL_VERIFYHOST => 0,
    	  CURLOPT_SSL_VERIFYPEER => 0,
    	  CURLOPT_CUSTOMREQUEST => "POST",
    	  CURLOPT_POSTFIELDS =>$params,
    	  CURLOPT_HTTPHEADER => $headers,
    	));

    	$response = curl_exec($curl);

    	curl_close($curl);
    	// print_r($response);
    	return trim($response);

    }

	// Order ID to be generated by your server
    echo json_encode(cashFreeOrderTokenGeneration($_POST['order_id'], $_POST['order_amount'], $_POST['order_currency'], true))

?>